SIM = verilator
TOPLEVEL_LANG = verilog
TOPLEVEL = chip_top
MODULE = test_cavlc_chip_top_rd

EXTRA_ARGS += -Wno-DECLFILENAME -Wno-WIDTHEXPAND -Wno-WIDTHTRUNC
EXTRA_ARGS += -Wno-UNUSEDSIGNAL -Wno-UNUSEDPARAM -Wno-BLKSEQ

VERILOG_SOURCES = \
  $(PWD)/rtl/integration/chip_top.v \
  $(PWD)/rtl/multiframe_codec_v2/axis_frame_ingest.v \
  $(PWD)/rtl/multiframe_codec_v2/block_packer.v \
  $(PWD)/rtl/multiframe_codec_v2/cavlc_enc.v \
  $(PWD)/rtl/multiframe_codec_v2/deblock_filter.v \
  $(PWD)/rtl/multiframe_codec_v2/intra_predict.v \
  $(PWD)/rtl/multiframe_codec_v2/mode_decision.v \
  $(PWD)/rtl/multiframe_codec_v2/output_byte_fifo.v \
  $(PWD)/rtl/multiframe_codec_v2/quantize_select.v \
  $(PWD)/rtl/multiframe_codec_v2/recon_context_store.v \
  $(PWD)/rtl/multiframe_codec_v2/stream_control.v \
  $(PWD)/rtl/multiframe_codec_v2/transform_select.v \
  $(PWD)/rtl/multiframe_codec_v2/zigzag_rle_select.v

export PYTHONPATH := $(PWD)/tb/rd:$(PWD):$(PWD)/examples/multiframe_codec_v2:/home/ubuntu/socmate-codec/venv/lib/python3.12/site-packages:$(PYTHONPATH)

include $(shell cocotb-config --makefiles)/Makefile.sim
