TOP = chip_top
BUILD_DIR ?= .socmate/rd_v2_cpp_build

VERILOG_SOURCES = \
  $(PWD)/rtl/integration/chip_top.v \
  $(PWD)/rtl/multiframe_codec_v2/axis_frame_ingest.v \
  $(PWD)/rtl/multiframe_codec_v2/block_packer.v \
  $(PWD)/rtl/multiframe_codec_v2/cavlc_enc.v \
  $(PWD)/rtl/multiframe_codec_v2/deblock_filter.v \
  $(PWD)/rtl/multiframe_codec_v2/intra_predict.v \
  $(PWD)/rtl/multiframe_codec_v2/mode_decision.v \
  $(PWD)/rtl/multiframe_codec_v2/output_byte_fifo.v \
  $(PWD)/rtl/multiframe_codec_v2/quantize_select.v \
  $(PWD)/rtl/multiframe_codec_v2/recon_context_store.v \
  $(PWD)/rtl/multiframe_codec_v2/stream_control.v \
  $(PWD)/rtl/multiframe_codec_v2/transform_select.v \
  $(PWD)/rtl/multiframe_codec_v2/zigzag_rle_select.v

all:
	verilator -cc --exe --build -Mdir $(BUILD_DIR) --top-module $(TOP) \
	  -Wno-DECLFILENAME -Wno-WIDTHEXPAND -Wno-WIDTHTRUNC \
	  -Wno-UNUSEDSIGNAL -Wno-UNUSEDPARAM -Wno-BLKSEQ \
	  $(VERILOG_SOURCES) $(PWD)/tb/rd/cavlc_v2_rd_main.cpp
