# =============================================================================
# Makefile -- socmate ASIC Build System
# =============================================================================
# Build flow from RTL to GDSII (RTL is generated by the LangGraph pipeline)
#
# Targets:
#   make lint        -- Run Verilator lint on all RTL
#   make sim         -- Run cocotb simulations (all blocks)
#   make synth       -- Run Yosys synthesis
#   make sta         -- Run OpenSTA timing analysis
#   make pnr         -- Run OpenLane place & route
#   make drc         -- Run Magic DRC
#   make lvs         -- Run netgen LVS
#   make gls         -- Run gate-level simulation
#   make power       -- Run power analysis
#   make all         -- Run complete flow
#   make clean       -- Remove build artifacts
#   make pipeline    -- Start LangGraph pipeline
#   make mcp         -- Start MCP server
# =============================================================================

PROJECT_ROOT := $(shell pwd)
PDK_ROOT ?= $(PROJECT_ROOT)/.pdk
VENV := $(PROJECT_ROOT)/venv
PYTHON := $(VENV)/bin/python

export PDK_ROOT

# RTL source files (generated by pipeline into rtl/)
RTL_ALL := $(wildcard rtl/**/*.v)

.PHONY: all lint sim synth sta pnr drc lvs gls power clean pipeline mcp test

# =============================================================================
# Complete flow
# =============================================================================
all: lint synth sta
	@echo "=== Full flow complete ==="

# =============================================================================
# Lint
# =============================================================================
lint:
	@echo "=== Running Verilator lint ==="
	@for f in $(RTL_ALL); do \
		echo "  Linting $$f..."; \
		verilator --lint-only -Wall $$f 2>&1 || true; \
	done
	@echo "=== Lint complete ==="

# =============================================================================
# Synthesis
# =============================================================================
synth:
	@echo "=== Running Yosys synthesis ==="
	@mkdir -p syn/output/top_level
	yosys -s syn/scripts/synth_top.ys 2>&1 | tee syn/output/top_level/yosys.log
	@echo "=== Synthesis complete ==="

# =============================================================================
# Static Timing Analysis
# =============================================================================
sta: synth
	@echo "=== Running OpenSTA ==="
	sta syn/scripts/power_analysis.tcl 2>&1 | tee syn/output/top_level/sta.log
	@echo "=== STA complete ==="

# =============================================================================
# Place & Route (OpenLane 2)
# =============================================================================
pnr: synth
	@echo "=== Running OpenLane 2 ==="
	cd pnr/openlane && ./run_openlane.sh
	@echo "=== P&R complete ==="

# =============================================================================
# DRC
# =============================================================================
drc:
	@echo "=== Running Magic DRC ==="
	@echo "DRC requires GDS from P&R step"

# =============================================================================
# LVS
# =============================================================================
lvs:
	@echo "=== Running netgen LVS ==="
	@echo "LVS requires GDS and netlist from P&R step"

# =============================================================================
# Gate-level simulation
# =============================================================================
gls: synth
	@echo "=== Running gate-level simulation ==="
	bash syn/scripts/gate_level_sim.sh

# =============================================================================
# Power analysis
# =============================================================================
power: synth
	@echo "=== Running power analysis ==="
	sta syn/scripts/power_analysis.tcl 2>&1 | tee syn/output/top_level/power.log

# =============================================================================
# LangGraph pipeline orchestrator
# =============================================================================
pipeline:
	@echo "=== Starting LangGraph ASIC pipeline ==="
	$(PYTHON) run_pipeline.py

mcp:
	@echo "=== Starting MCP server ==="
	$(PYTHON) -m orchestrator.mcp_server

# =============================================================================
# Tests
# =============================================================================
test:
	$(PYTHON) -m pytest orchestrator/tests/ -v

# =============================================================================
# Clean
# =============================================================================
clean:
	rm -rf sim_build/
	rm -rf syn/output/
	rm -rf pnr/output/
	@echo "Build artifacts cleaned"
