# Copyright (c) Meta Platforms, Inc. and affiliates.
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

# =============================================================================
# Makefile -- socmate ASIC Build System
# =============================================================================
# Thin wrapper around the LangGraph-orchestrated pipeline.
#
# All real EDA work (synthesis, sim, PnR, DRC, LVS, STA) is driven by the
# pipeline graphs in orchestrator/langgraph/, which generate per-block Yosys
# scripts, SDC files, OpenROAD Tcl, etc. on the fly into syn/output/<block>/
# and pnr/output/<block>/. There are no static syn/scripts/ or pnr/openlane/
# files in this repo; older releases shipped them but they are now generated.
#
# Targets:
#   make pipeline    -- Run frontend pipeline (architecture + RTL + sim + synth)
#   make backend     -- Run backend pipeline (PnR + DRC + LVS + signoff)
#   make mcp         -- Start the MCP server for interactive use with Claude CLI
#   make lint        -- Run Verilator lint on every generated rtl/**/*.v file
#   make test        -- Run the orchestrator unit tests
#   make preflight   -- Validate PDK + EDA tools are installed before a run
#   make clean       -- Remove all generated build artifacts
# =============================================================================

PROJECT_ROOT := $(shell pwd)
PDK_ROOT ?= $(PROJECT_ROOT)/.pdk
VENV ?= $(PROJECT_ROOT)/venv

# Resolve python: prefer the project venv, fall back to whatever is on PATH so
# users who installed via `scripts/install_toolchain.sh` (which creates the
# venv at orchestrator/.venv) or via `pip install -e .` globally still work.
ifeq ($(wildcard $(VENV)/bin/python),)
  ifneq ($(wildcard $(PROJECT_ROOT)/orchestrator/.venv/bin/python),)
    PYTHON := $(PROJECT_ROOT)/orchestrator/.venv/bin/python
  else
    PYTHON := python3
  endif
else
  PYTHON := $(VENV)/bin/python
endif

export PDK_ROOT

# RTL source files generated by the pipeline into rtl/<block>/<name>.v
RTL_ALL := $(shell find rtl -name '*.v' 2>/dev/null)

.PHONY: all pipeline backend mcp tapeout lint test preflight clean help

# Default target: print usage. Avoids a confusing "no rule" error for users
# who type `make` expecting something to happen.
all: help

help:
	@echo "socmate ASIC Build System"
	@echo ""
	@echo "Primary entry points:"
	@echo "  make pipeline   -- Run frontend pipeline headlessly (auto-resume on interrupts)"
	@echo "  make backend    -- Run backend pipeline (PnR + signoff) on synthesized blocks"
	@echo "  make mcp        -- Start MCP server for interactive use with Claude CLI"
	@echo ""
	@echo "Utilities:"
	@echo "  make preflight  -- Check PDK + EDA toolchain readiness"
	@echo "  make lint       -- Verilator lint on every generated rtl/**/*.v"
	@echo "  make test       -- Run unit tests"
	@echo "  make clean      -- Remove generated artifacts"
	@echo ""
	@echo "Tip: synthesis/STA/PnR/DRC/LVS scripts are generated by the pipeline"
	@echo "into syn/output/<block>/ and pnr/output/<block>/ -- there is no"
	@echo "static 'make synth' / 'make pnr' target. Use 'make pipeline' or"
	@echo "'make backend' instead."

# =============================================================================
# Preflight: validate PDK + tools before burning time on a real run
# =============================================================================
preflight:
	@echo "=== Running preflight check ==="
	@$(PYTHON) -c "from orchestrator.langgraph.pipeline_helpers import preflight_check; \
import json, sys; \
r = preflight_check(['pipeline', 'backend']); \
print(json.dumps(r, indent=2)); \
sys.exit(0 if r['ok'] else 1)"

# =============================================================================
# Lint -- Verilator lint on every generated RTL file
# =============================================================================
lint:
	@echo "=== Running Verilator lint on $(words $(RTL_ALL)) RTL files ==="
	@if [ -z "$(RTL_ALL)" ]; then \
		echo "  No RTL files found under rtl/. Run 'make pipeline' first."; \
	fi
	@for f in $(RTL_ALL); do \
		echo "  Linting $$f..."; \
		verilator --lint-only -Wall -Wno-fatal -Wno-EOFNEWLINE $$f 2>&1 || true; \
	done
	@echo "=== Lint complete ==="

# =============================================================================
# LangGraph pipelines
# =============================================================================
pipeline:
	@echo "=== Starting LangGraph frontend pipeline ==="
	$(PYTHON) run_pipeline.py

# The backend and tapeout graphs do not have a headless CLI runner --
# they're driven through the MCP server's start_backend / start_tapeout
# tools. Run `make mcp` and invoke the tool from Claude CLI / Cursor.
backend tapeout:
	@echo ""
	@echo "  The $@ pipeline runs through the MCP server, not as a CLI."
	@echo "  In one terminal: make mcp"
	@echo "  Then from Claude CLI / Cursor, call the start_$@ MCP tool."
	@echo ""
	@false

mcp:
	@echo "=== Starting MCP server ==="
	$(PYTHON) -m orchestrator.mcp_server

# =============================================================================
# Tests
# =============================================================================
test:
	$(PYTHON) -m pytest orchestrator/tests/ -v -m "not live_llm and not requires_nix and not e2e"

test-all:
	$(PYTHON) -m pytest orchestrator/tests/ -v

# =============================================================================
# Clean
# =============================================================================
clean:
	rm -rf sim_build/
	rm -rf syn/output/
	rm -rf pnr/output/
	rm -rf .socmate/step_logs/
	@echo "Build artifacts cleaned (rtl/, tb/, arch/ preserved)"

distclean: clean
	rm -rf rtl/ tb/ arch/ verification/ .socmate/
	@echo "Full distclean complete"
